---
# This playbook deploys a simple standalone Tomcat 7 server.

- hosts: tom
  remote_user: root
  become: yes
  become_method: sudo
  pre_tasks:
    - debug: msg={{http_port}}
  roles:
    - selinux
    - tomcat
  vars:
    http_port: 8080
    https_port: 8443
