---
- name: Install Java 1.8
  yum: name=java-1.8.0-openjdk state=present

- name: add group "tomcat"
  group: name=tomcat

- name: add user "tomcat"
  user: name=tomcat group=tomcat home=/usr/share/tomcat createhome=no
  become: True
  become_method: sudo

#- name: Download Tomcat
# get_url: url=http://archive.apache.org/dist/tomcat/tomcat-8/v8.0.30/src/apache-tomcat-8.0.30-src.tar.gz dest=/opt/apache-tomcat

- name: Extract archive
  command: chdir=/usr/share /bin/tar xvf /opt/apache-tomcat-7.0.61.tar.gz -C /opt/ creates=/opt/apache-tomcat

- name: Symlink install directory
  file: src=/opt/apache-tomcat-7.0.61 path=/usr/share/tomcat state=link

- name: Change ownership of Tomcat installation
  file: path=/usr/share/tomcat/ owner=tomcat group=tomcat state=directory recurse=yes

- name: Configure Tomcat server
  template: src=server.xml dest=/usr/share/tomcat/conf/
  notify: restart tomcat

- name: Configure Tomcat users
  template: src=tomcat-users.xml dest=/usr/share/tomcat/conf/
  notify: restart tomcat

- name: Install Tomcat init script
  copy: src=tomcat-initscript.sh dest=/etc/init.d/tomcat mode=0755

- name: Start Tomcat
  service: name=tomcat state=started enabled=yes

- name: Install firewalld
  yum: name={{ item }} state=latest
  with_items:
    - firewalld
    - ipset

#- name: Enable firewalld
#  service: name=firewalld state=started enabled=yes

#- name: insert firewalld rule for tomcat http port
#  firewalld: port=8080/tcp permanent=true state=enabled immediate=yes
 

#- name: insert firewalld rule for tomcat https port
#  firewalld: port={{ https_port }}/tcp permanent=true state=enabled immediate=yes
  

#- name: wait for tomcat to start
#  wait_for: port={{http_port}}

- name: Copy WAR file
  copy: src=hiapp.war dest=/usr/share/tomcat/webapps/ mode=0644 owner=tomcat group=tomcat
  
#- name: Copy WAR file
#  copy: src=hiapp.war dest=/var/lib/tomcat/webapps/ mode=0644 owner=tomcat group=tomcat
